### ISSUE TITLE
BFS seems to have an error.Please help!

### ISSUE THREAD

**Issue by CinderaLuo** [JianlongZhong/Medusa#1]
I use the several datasets downloaded at https://code.google.com/p/medusa-gpu/.  The total steps of BFS algorithm is 1 no matter what kind of datasets I use.There is seems wrong .
And I use the command "./test 1 1 ../dataset/random.1mv.16me  text.txt" to run BFS alogrithm  in MedusaTemplate/MBFS. My cuda version is 5.5,and cudpp is 2.0. Am I missing something?Please help.

**Comment by kongfujianlong** [comment]
Medusa is not tested under 5.5 and is not guaranteed to work under 5.5. However, I currently do not have time to upgrade it. Regarding your error, the datasets you downloaded is tested and manually verified when I did the experiments. I suggest you do some debugging to see (1) if the kernel is really called; (2) if the data loading has any problem. Thanks.

**Comment by CinderaLuo** [comment]
I think the version of cuda is not  the key reason,because I have compiled your program. Also I check whether the kernel is called.I found that FunctorHolder<VERTEX>::Run(uv) is called when I use one GPU. Also I print the values of "gpu_def[0].edgeArray.size" and "gpu_def[0].vertexArray.size"before the kernel runs .The size of edge array is right. The size of vertex array is always 0. I think you write the many versions of kernel which is edge-centric and vertex-centric.  I just find the function building edge array,but can not find the function really building vertex array.Maybe this is the key reason that the step of BFS is always 1. Or Maybe Medusa can not run on one GPU. Please help.

**Comment by CinderaLuo** [comment]
Why even through I use the dataset in your github to run PageRank, there always shows the error message "Before convert to MEG, the GraphIR must be sorted". Did you have the code to convert the input file?Please help.

**Comment by CinderaLuo** [comment]
Your iteration step of pagerank is set as 100,and you do not use the tolerance of PR to make the execution done. Am I right?

**Comment by kongfujianlong** [comment]
The current PG implementation uses a fixed number of iterations. You can easily change to use the maximum difference as termination condition.

**Comment by CinderaLuo** [comment]
Can you tell me how to change to use the maximum difference as termination condition in detail?Please help.
