### ISSUE TITLE
Always segmentation error, please give me some suggestions

### ISSUE THREAD

**Issue by alex031029** [JianlongZhong/Medusa#2]
I can cmake and make the Medusa under Ubuntu 14.04. But when I ran $./test 1 1 ../datasets/random.1mv.16me ../datasets/random.1mv.16me for BFS, it always got segmentation error. Right after the info "GPU 0 enter", I got segmentation error (core dumped). 

I have shifted my CUDA to version 4.5, and use cudpp 2.0 instead of new version 2.2, but it doesn't work. 

I appreciate a lot if you could offer some suggestions!

**Comment by kongfujianlong** [comment]
Could you use gdb and provide the stack trace?

**Comment by alex031029** [comment]
I have sent you an email to your NTU address. Since you didn't reply me via email, I attached the gdb result below. Thanks!


(gdb) r 1 1 ../datasets/random.1mv.16me ../datasets/random.1mv.16me
Starting program: /home/syc/GPU/Medusa/Algorithm/test 1 1 ../datasets/random.1mv.16me ../datasets/random.1mv.16me
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> GPU 0  Tesla K20c has asyncEngineCount 2 13
[New Thread 0x7ffff57a8700 (LWP 61299)]
start to add edge
gp_array[0].replica_edge_index[0] = 16000000
total number of stored edges 16000000
level 0: 0 vertex 0 edge
GPU 0 enter

Program received signal SIGSEGV, Segmentation fault.
0x0000000000409849 in EdgeArray::buildAA(GraphIR&) ()
