### ISSUE TITLE
What are the dependencies of Medusa?

### ISSUE THREAD

**Issue by sgpyc** [JianlongZhong/Medusa#6]
Hi, I would like to compile and run Medusa for comparison purpose.
However, I can't find the dependency list of the project.
From SSSP/Makefile, it seems like cudpp2.0 and cuda 5.0 with SDK sample are required.
cudpp2.0 is fine, although it's a old version and requires changing the "GENCODE" parameter to get it working under newer CUDA version and hardware.

However, CUDA 5.0 is too old to work with. Is there any way to make Medusa compilable with newer version of CUDA (say >= 6.0, best to be >=7.5)?

**Comment by kongfujianlong** [comment]
You may refer to this pull request https://github.com/JianlongZhong/Medusa/pull/4
It has upgraded Medusa to cuda7.5 and cudpp to 2.2.

**Comment by sgpyc** [comment]
Thanks for the fast response.

I found Makefile under Algorithm, MBFS, MPG and SSSP, but CMakeLists.txt only under Algorithm.
Perviously I tried to run "make" directly under SSSP (which invoke SSSP/Makefile), runs into errors.
I also tried to use the CMakeLists.txt under Algorithm by cmake 3.3.0, and run make (with CUDA 7.5.17 + gcc 4.8.5 + ubuntu 14.04), it complains about not finding helper_cuda.h, referenced by Algorithm/MessageDataType.h. 

Algorithm/CMakeList.txt use /home/cheyulin/... in CUDA_SDK_UTIL_PTH and CUDPP_PATH, and I think that's where the error comes from.
After changing these two to the correct paths, make generated a branch of warnings, and can't find cudppCreate and cudppPlan in the linking stage.

[Medusa_make.txt](https://github.com/JianlongZhong/Medusa/files/535055/Medusa_make.txt)

Please advise on the process to get it compiled.
Also, the Algorithm/CMakeList.txt seems only care about MBFS. Can it also be applied to MPG and SSSP?

**Comment by sgpyc** [comment]
By the way, is the generated code 32bit or 64bit? I can't find the indicator in CMakeList.txt.
cudpp sets 32bit or 64bit compilation by CMAKE_SIZEOF_VOID_P, and the latest NVIDIA linux driver won't allow 32bit program to run on Telsa cards.
