### ISSUE TITLE
The format of partition file 

### ISSUE THREAD

**Issue by CinderaLuo** [JianlongZhong/Medusa#8]
Hi!
I am interested in the performance of Medusa when running on multiple GPU. But I have no idea about where the partition file comes from and the format of the partition file. 
Please help!

**Comment by kongfujianlong** [comment]
Hi,

1. you have to generate partition by yourself. You can use some graph partitioning algorithm, or simply use hash partition.
2. for each vertex, you need to generate a partition ID. The partition file looks like below:
0
0
1
1
..
meaning: vertex ID 1,2 (same as line number) is in partition 0; vertex ID 3,4 is in partition 1 ...

**Comment by CinderaLuo** [comment]
Thanks a lot !
I think if the Vertex ID 1 is in partition 0 , 1 and 2, then the partition file seems look like below:
0, 1, 2
...
Am I right?

**Comment by kongfujianlong** [comment]
Yes.
